In [1]:
import numpy as np
import random
import copy
import sys

In [2]:
def MAT(): # вводим матрицу системы с клавиатуры, плюс правая часть. 
    print("Введите колиичество уравнений: ", end="")
    n = int(input())
    Mat = np.zeros((n, n)) #создам нулевую матрицу размерности n*n
    B = np.zeros((n, 1)) #создам нулевую матрицу размерности 1*n
    print('Введите коэффициенты системы построчно:')
    for i in range (n):
        for j in range (n):
            Mat[i][j] = float(input())
    print('введите коэффициенты правой части:')
    for j in range (n):
        B[j] = float(input())
    initialA = copy.copy(Mat) #глубокая копия матрицы которая не меняеться. 
    initialB = copy.copy(B)
    print('Матрица системы A имеет вид:\n', Mat)
    print('Матрица право части B имеет вид:\n', B)
    return Mat,B,initialA,initialB

In [3]:
def max1(matrix,j): #j это номер столбика где мы ищем максимум
    max1 = matrix[j][j]
    k = j # номер строки где будет максимум
    for i in range(j+1, len(matrix)): #перебираем строки
        if (abs(matrix[i][j]) > abs(max1)):
            max1 = matrix[i][j]
            k = i
    return max1,k
#функция возвращает кортедж двух елементов вытащить их Y=(max1(A,i)) Y[0] Y [1]

In [4]:
A = np.random.randint(1, 100, size=(5, 5)) #создание случайной матрицы.
print(A)
print(len(A))
for i in range (len(A)-1):
    Y=(max1(A,i))
    print(Y)
    print(Y[1])
print(type(Y))

[[79 93  2 84 23]
 [91 46 67 29  3]
 [35  2 67 40 64]
 [ 9 13 53 28 32]
 [67 96  2 47 74]]
5
(91, 1)
1
(96, 4)
4
(67, 2)
2
(47, 4)
4
<class 'tuple'>


In [5]:
def swaprows(matrix,i,j): # замена i-го рядка на j-тый в матрице matrix
    matrix[i], matrix[j] = matrix[j], matrix[i].copy() # смена рядков матрицы местами.
    return matrix

In [12]:
def Gausse(matrix,B):
    num = 0 # индикатор количества перестановок рядков для знака определиеля
    a=0
    for i in range (len(matrix)):
       # print(matrix)
        if a==1:
            break
        Y=(max1(matrix,i))
        if Y[0] != 0:  # машинный ноль. 
            #Y[0] == sys.float_info.epsilon:  # машинный ноль. 
            if Y[0] != matrix[i][i]:
                swaprows(matrix,i,Y[1])   
                swaprows(B,i,Y[1])
                print('Меняем рядки\n',matrix)
                num += 1
                
                for p in range (i+1,len(matrix)):    
                    t = matrix[p][i]/matrix[i][i]
                    B[p] = B[p] - t * B[i]
                    matrix[p][i] = 0
                    for l in range (i+1,len(matrix)):
                        matrix[p][l] = matrix[p][l] - t * matrix[i][l]
            print(matrix)
        
        elif Y[0] == 0:
            print('Проблемы начинаються с',i + 1,'-го ряда')
            a=1
            break
        #print(matrix)
        print(B)
    print('количество замен рядков',num)
    return matrix, B

In [ ]:
Mat, B, initialA, initialB= MAT()

Введите колиичество уравнений: 

In [6]:
# проверка работы функции смены рядков
A = np.random.randint(1, 100, size=(7, 7)) #создание случайной матрицы.
B = np.random.randint(1, 100, size=(7, 1))
#print(A)
print('')
#print('Смена 3 и 4 рядка:')
#swaprows(A,2,3)
print(A)
print (B)


[[99 35 38 33 17 33 94]
 [66 32 96 27 87 53 53]
 [ 7 24 35 24 74 43 59]
 [33 44 31 91 73 82 64]
 [24 87 67 43 26 90  5]
 [45 96 24 48  2 22 68]
 [20 28 19 32 77 72  7]]
[[43]
 [85]
 [60]
 [64]
 [65]
 [56]
 [33]]


In [12]:
Gausse(A,B)

[[21 82 22 97 89 65 81]
 [67 70 25 39 53 40 24]
 [59 62 73 24  1 18 58]
 [ 1 14 60 27 17  7 56]
 [38 40 91 29 12 99 80]
 [29 76 96 37 81 18 86]
 [63  8 88 86 10 29 13]]
Меняем рядки
 [[67 70 25 39 53 40 24]
 [21 82 22 97 89 65 81]
 [59 62 73 24  1 18 58]
 [ 1 14 60 27 17  7 56]
 [38 40 91 29 12 99 80]
 [29 76 96 37 81 18 86]
 [63  8 88 86 10 29 13]]
[[ 67  70  25  39  53  40  24]
 [  0  60  14  84  72  52  73]
 [  0   0  50 -10 -45 -17  36]
 [  0  12  59  26  16   6  55]
 [  0   0  76   6 -18  76  66]
 [  0  45  85  20  58   0  75]
 [  0 -57  64  49 -39  -8  -9]]
[[ 67  70  25  39  53  40  24]
 [  0  60  14  84  72  52  73]
 [  0   0  50 -10 -45 -17  36]
 [  0   0  56   9   1  -4  40]
 [  0   0  76   6 -18  76  66]
 [  0   0  74 -43   4 -39  20]
 [  0   0  77 128  29  41  60]]
Меняем рядки
 [[ 67  70  25  39  53  40  24]
 [  0  60  14  84  72  52  73]
 [  0   0  77 128  29  41  60]
 [  0   0  56   9   1  -4  40]
 [  0   0  76   6 -18  76  66]
 [  0   0  74 -43   4 -39  20]
 [  0   0  5

(array([[  67,   70,   25,   39,   53,   40,   24],
        [   0,   60,   14,   84,   72,   52,   73],
        [   0,    0,   77,  128,   29,   41,   60],
        [   0,    0,    0, -166,  -23,  -78,  -37],
        [   0,    0,    0,    0,  -50,    0,   18],
        [   0,    0,    0,    0,    0,   91,   21],
        [   0,    0,    0,    0,    0,    0,   10]]), array([[ 37],
        [ -1],
        [ 22],
        [ 31],
        [-56],
        [  0],
        [-17]]))

In [9]:
Mat2 = Gausse(Mat,B)
#print((Mat2))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [13]:
Ak = np.array([[5, 0, 7, 0],[-1, 6, 0, 1],[2, -6, -4, -5],[-6, -6, 15, 7]])
print (Ak)
Bk1 = np.array([-123, 60, -108, 159])
Bk= Bk1.transpose()
print (Bk)

print('')

Ae = np.array([[-5, 0, 7, 0],[4, 6, 0, 1],[3, 12, -7, -23],[-2, 42, 37, -21]])
print (Ae)
Be1 = np.array([109, 168, -193, -95])
Be = Be1.transpose()
print (Be) 

[[ 5  0  7  0]
 [-1  6  0  1]
 [ 2 -6 -4 -5]
 [-6 -6 15  7]]
[-123   60 -108  159]

[[ -5   0   7   0]
 [  4   6   0   1]
 [  3  12  -7 -23]
 [ -2  42  37 -21]]
[ 109  168 -193  -95]


In [14]:
Gausse(Ak,Bk)

Меняем рядки
 [[-6 -6 15  7]
 [-1  6  0  1]
 [ 2 -6 -4 -5]
 [ 5  0  7  0]]
[[-6 -6 15  7]
 [ 0  7 -2  0]
 [ 0 -8  1 -2]
 [ 0 -5 19  5]]
[159  33 -55   9]
Меняем рядки
 [[-6 -6 15  7]
 [ 0 -8  1 -2]
 [ 0  7 -2  0]
 [ 0 -5 19  5]]
[[-6 -6 15  7]
 [ 0 -8  1 -2]
 [ 0  0 -1 -1]
 [ 0  0 18  6]]
[159 -55 -15  43]
Меняем рядки
 [[-6 -6 15  7]
 [ 0 -8  1 -2]
 [ 0  0 18  6]
 [ 0  0 -1 -1]]
[[-6 -6 15  7]
 [ 0 -8  1 -2]
 [ 0  0 18  6]
 [ 0  0  0  0]]
[159 -55  43 -12]
Проблемы начинаються с 4 -го ряда
количество замен рядков 3


(array([[-6, -6, 15,  7],
        [ 0, -8,  1, -2],
        [ 0,  0, 18,  6],
        [ 0,  0,  0,  0]]), array([159, -55,  43, -12]))

In [9]:
Gausse(Ae,Be)

NameError: name 'Gausse' is not defined